#!/bin/bash
# =========================================================
# Taskfile gives you a set of quick tasks for your project
# More info: https://github.com/Enrise/Taskfile
# =========================================================

function banner {
	echo -e "${BLUE}\n"\
	"▗▄▄▄ ▗▖  ▗▖▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖ ▗▄▄▖   ▗▄▄▄▖▗▄▄▖    ▗▄▄▄▖▗▄▄▄▖▗▖  ▗▖▗▄▄▄▖▗▄▄▖ \n"\
	"▐▌  █ ▝▚▞▘ ▐▛▚▖▐▌▐▌ ▐▌▐▛▚▞▜▌  █  ▐▌        █  ▐▌ ▐▌   ▐▌     █   ▝▚▞▘ ▐▌   ▐▌ ▐▌\n"\
	"▐▌  █  ▐▌  ▐▌ ▝▜▌▐▛▀▜▌▐▌  ▐▌  █  ▐▌        █  ▐▛▀▘    ▐▛▀▀▘  █    ▐▌  ▐▛▀▀▘▐▛▀▚▖\n"\
	"▐▙▄▄▀  ▐▌  ▐▌  ▐▌▐▌ ▐▌▐▌  ▐▌▗▄█▄▖▝▚▄▄▖   ▗▄█▄▖▐▌      ▐▌   ▗▄█▄▖▗▞▘▝▚▖▐▙▄▄▖▐▌ ▐▌${RESET}"
}

# =========================================================
## Project
# =========================================================

function task:init { ## Initialise the project for local development
	project:git-config
	project:update
	task:help
}

function task:start { ## Start the project in development mode
	title "Run development application"
	deno run -A --watch main.ts
}

function task:update { ## Update all dependencies and files
	project:git-config
	project:update
}

function project:update {
	title "Run project updates"
	echo "Running deno install."
	deno install
}

function project:git-config {
	title "Setting git configuration"
	git config --local core.hooksPath dev/git-hooks
	echo -e "Git hooks directory is set to ${YELLOW}./dev/git-hooks${RESET}."
}

function task:pr { ## Check out pull request <number> and update
	project:checkout-pr $1
	project:update
}

function project:checkout-pr {
	title "Checking out pull request"
	if [ -z "$1" ]; then
		echo "You need to provide a pull request number to check out."
		echo -e "${BLUE}Usage:${RESET} $0 pr ${YELLOW}<number>${RESET}"
		exit 1
	fi
	echo "Checking out pull request $1..."
	git fetch origin refs/pull/$1/head:refs/remotes/origin/pr/$1
	git checkout origin/pr/$1
}

# =========================================================
## Docker
# =========================================================

function task:build { ## Build the production container
	title "Buidling latest container"
	docker build --tag futureportal/transip-dynamic-ip-fixer:latest .
}

function task:latest { ## Run the latest production container
	title "Running latest container"
	docker run --rm -ti \
		--volume ./records.json:/opt/futureportal/transip-dynamic-ip-fixer/records.json \
		--volume ./transip.key:/opt/futureportal/transip-dynamic-ip-fixer/transip.key \
		futureportal/transip-dynamic-ip-fixer:latest
}

function task:publish { ## Publish the production container to the docker hub
	title "Pushing latest container"
	docker push futureportal/transip-dynamic-ip-fixer:latest
}

# =========================================================
## Taskfile
# =========================================================

set -eo pipefail

BLUE=$(printf '\033[36m')
YELLOW=$(printf '\033[33m')
RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
RESET=$(printf '\033[0m')

# Define global variables here

function title {
	echo -e "\n${BLUE}=>${RESET} $1\n"
}

function task:help { ## Show all available tasks
	title "Available tasks"
	awk 'BEGIN {FS = " { [#][#][ ]?"} /^([a-zA-Z_-]*:?.*)(\{ )?[#][#][ ]?/ \
		{printf "\033[33m%-34s\033[0m %s\n", $1, $2}' $0 |\
		sed -E "s/[#]{2,}[ ]*/${RESET}/g" |\
		sed -E "s/function task:*/  /g"
	echo -e "\n${BLUE}Usage:${RESET} $0 ${YELLOW}<task>${RESET} <args>"
}

function task:shorthand { ## Create CLI shorthand task instead of ./Taskfile
	title "Creating task shorthand"
	echo -e "You're about to create ${YELLOW}/usr/local/bin/task${RESET} that requires ${RED}root${RESET} permission..."
	sudo curl --location --silent --output /usr/local/bin/task https://enri.se/taskfile-bin
	sudo chmod +x /usr/local/bin/task
	echo -e "${BLUE}You can now use:${RESET} task ${YELLOW}<task>${RESET} <args>"
}

banner
if [[ ! "$(declare -F task:${@-help})" ]]; then
	title "Task not found"
	echo -e "Task ${RED}$1${RESET} doesn't exist."
	task:help
	exit 1
fi
task:${@-help}
